from term import Term


# greek alphabet: small letters
sym_alpha = Term("\\alpha")
sym_beta = Term("\\beta")
sym_gamma = Term("\\gamma")
sym_delta = Term("\\delta")
sym_epsilon = Term("\\epsilon")
sym_zeta = Term("\\zeta")
sym_eta = Term("\\eta")
sym_theta = Term("\\theta")
sym_iota = Term("\\iota")
sym_kappa = Term("\\kappa")
sym_lambda = Term("\\lambda")
sym_mu = Term("\\mu")
sym_nu = Term("\\nu")
sym_xi = Term("\\xi")
sym_pi = Term("\\pi")
sym_rho = Term("\\rho")
sym_sigma = Term("\\sigma")
sym_tau = Term("\\tau")
sym_upsilon = Term("\\upsilon")
sym_phi = Term("\\phi")
sym_chi = Term("\\chi")
sym_psi = Term("\\psi")
sym_omega = Term("\\omega")

# greek alphabet: capital letters
sym_Alpha = Term("\\Alpha")
sym_Beta = Term("\\Beta")
sym_Gamma = Term("\\Gamma")
sym_Delta = Term("\\Delta")
sym_Epsilon = Term("\\Epsilon")
sym_Zeta = Term("\\Zeta")
sym_Eta = Term("\\Eta")
sym_Theta = Term("\\Theta")
sym_Iota = Term("\\Iota")
sym_Kappa = Term("\\Kappa")
sym_Lambda = Term("\\Lambda")
sym_Mu = Term("\\Mu")
sym_Nu = Term("\\Nu")
sym_Xi = Term("\\Xi")
sym_Pi = Term("\\Pi")
sym_Rho = Term("\\Rho")
sym_Sigma = Term("\\Sigma")
sym_Tau = Term("\\Tau")
sym_Upsilon = Term("\\Upsilon")
sym_Phi = Term("\\Phi")
sym_Chi = Term("\\Chi")
sym_Psi = Term("\\Psi")
sym_Omega = Term("\\Omega")
